# Generated by Django 4.2.7 on 2026-05-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judcd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='actions/'),
        ),
        migrations.AlterField(
            model_name='galerie_action',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='galerie/'),
        ),
        migrations.AlterField(
            model_name='membre_equipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipe/'),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='temoignages/'),
        ),
    ]
