# Generated by Django 4.2.7 on 2026-05-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judcd_app', '0002_alter_action_image_couverture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('profession', models.CharField(max_length=100, verbose_name='Profession')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EXPIREE', 'Expirée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Montant payé')),
                ('capture_depot', models.ImageField(upload_to='adhesions/preuves/', verbose_name='Preuve de dépôt')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('motivations', models.TextField(verbose_name='Motivations pour adhérer')),
                ('competences', models.TextField(blank=True, verbose_name='Compétences et expériences')),
                ('disponibilites', models.TextField(blank=True, verbose_name='Disponibilités')),
                ('commentaires_admin', models.TextField(blank=True, verbose_name='Commentaires administrateur')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création de la demande'), ('APPROBATION', 'Approbation'), ('REJET', 'Rejet'), ('RENOUVELLEMENT', 'Renouvellement'), ('EXPIRATION', 'Expiration')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('commentaires', models.TextField(blank=True)),
                ('adhesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='judcd_app.adhesion')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'adhésion",
                'verbose_name_plural': "Historiques d'adhésions",
                'ordering': ['-date_action'],
            },
        ),
    ]
