# Generated by Django 4.2.7 on 2026-05-10 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judcd_app', '0003_adhesion_historiqueadhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerie_action',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galerie_action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galerie_action',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galerie_action',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
